# Generated by Django 5.0.7 on 2024-10-01 05:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="description",
            new_name="job_description",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="location",
            new_name="posting_title",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_on",
        ),
        migrations.RemoveField(
            model_name="job",
            name="title",
        ),
        migrations.AddField(
            model_name="job",
            name="account_manager",
            field=models.CharField(
                blank=True, default="Venkateswarlu Sunke", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="actual_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="address_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="address_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="address_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="assigned_recruiter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="date_opened",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="expected_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                blank=True, default="In-progress", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True, default="Full time", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="missed_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="number_of_positions",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="revenue_per_position",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="target_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="job",
            name="work_experience",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
